export const labels = {
  meta: {
    title: "Home Manager",
    description: "Home management control panel.",
  },
  common: {
    panelActiveLabel: "active panel",
    homesActiveLabel: "active homes",
    vehiclesActiveLabel: "active vehicles",
    backToHome: "Back to home",
    backToPanel: "Back to panel",
    backToSelector: "Back to selector",
    backToList: "Back to list",
    backToVehicle: "Back to vehicle",
    open: "Open",
    view: "View",
    viewDetail: "View details",
    openPanel: "Open panel",
    viewBills: "View bills",
    soon: "Coming soon",
    emptyValue: "-",
    noExtraDetails: "No extra details",
    noAdditionalDetails: "No additional details.",
    languageLabel: "Language",
    languageOptions: {
      es: "Spanish",
      en: "English",
    },
  },
  dashboard: {
    eyebrow: "Control panel",
    title: "Select your home to manage your household",
    description:
      "See bills, consumption, and tasks in one place. Each home has its own control space.",
    panelCode: "HM",
    homesSectionTitle: "Homes",
    homesCardTitle: "Home selector",
    homesCardDescription: "Access each home's panel with bills, consumption, and pending tasks.",
    homesLinkLabel: "View homes",
    vehiclesSectionTitle: "Vehicles",
    vehiclesCardTitle: "Maintenance control",
    vehiclesCardDescription: "Check your cars, workshops, and expenses in one place.",
    vehiclesLinkLabel: "View vehicles",
    nextStepEyebrow: "Next step",
    nextStepTitle: "Connect electricity bills and review costs by home",
    nextStepDescription:
      "Define providers and cost categories to get a detailed monthly breakdown.",
    nextStepTag: "Coming soon",
  },
  homes: {
    eyebrow: "Homes",
    title: "Select your home to manage your household",
    description:
      "See bills, consumption, and tasks in one place. Each home has its own control space.",
    selectorTitle: "Home selector",
    cardBadge: "Home",
    cardDescription: "Direct access to bills, consumption, and maintenance.",
  },
  homeDetail: {
    eyebrow: "Home",
    description: "Quick access to the home's main sections.",
    servicesTitle: "Main services",
    tiles: {
      energy: {
        title: "Electricity",
        description: "Bills and electricity consumption.",
        action: "Open",
      },
      water: {
        title: "Water",
        description: "Bills and consumption tracking.",
        action: "Open",
      },
      gas: {
        title: "Gas",
        description: "Gas billing and consumption.",
        action: "Open",
      },
      insurance: {
        title: "Insurance",
        description: "Policies and renewals.",
        action: "Coming soon",
      },
    },
  },
  vehicles: {
    eyebrow: "Vehicles",
    title: "Manage your household fleet",
    description: "View records and recent maintenance for each car.",
    listTitle: "Registered vehicles",
    emptyList: "No vehicles registered yet.",
    cardBadge: "Vehicle",
    statLabel: "maintenance",
    defaultIcon: "V",
  },
  energy: {
    eyebrow: "Electricity",
    titlePrefix: "Bills for",
    description: "Review electricity billing amounts and periods.",
    listTitle: "Bill list",
    emptyList: "No bills registered yet.",
    chartTitle: "Electricity consumption",
    chartSubtitle: "kWh and amount per bill",
    chartEmpty: "No consumption recorded to display.",
    chartSeriesKwh: "Consumption (kWh)",
    chartSeriesAmount: "Amount (€)",
    chartAxisKwh: "kWh",
    chartAxisAmount: "€",
    comparison: {
      title: "Yearly comparison",
      description: "Monthly amounts, consumption, and average €/kWh.",
      empty: "Not enough data to compare 2024 and 2025.",
      actionLabel: "View comparison",
      deltaLabel: "Difference",
      chartTitle: "Monthly comparison",
      chartSubtitle: "Overlaid lines by year",
      chartMetricLabel: "Metric",
      chartMetricAmount: "Amount",
      chartMetricKwh: "kWh",
      chartAxisAmount: "€",
      chartAxisKwh: "kWh",
      filters: {
        yearA: "Base year",
        yearB: "Compared year",
        apply: "Apply",
      },
      columns: {
        month: "Month",
        amount: "Amount",
        kwh: "Consumption",
        eurPerKwh: "€/kWh",
        bill: "Bill",
        deltaAmount: "Δ Amount",
        deltaKwh: "Δ kWh",
      },
    },
  },
  water: {
    eyebrow: "Water",
    titlePrefix: "Bills for",
    description: "Review water billing amounts and periods.",
    listTitle: "Bill list",
    emptyList: "No bills registered yet.",
    chartTitle: "Water consumption",
    chartSubtitle: "m³ and amount per bill",
    chartEmpty: "No consumption recorded to display.",
    chartSeriesM3: "Consumption (m³)",
    chartSeriesAmount: "Amount (€)",
    chartAxisM3: "m³",
    chartAxisAmount: "€",
  },
  gas: {
    eyebrow: "Gas",
    titlePrefix: "Bills for",
    description: "Review gas billing amounts and periods.",
    listTitle: "Bill list",
    emptyList: "No bills registered yet.",
    chartTitle: "Gas consumption",
    chartSubtitle: "kWh and m³ per bill",
    chartEmpty: "No consumption recorded to display.",
    chartSeriesKwh: "Consumption (kWh)",
    chartSeriesM3: "Consumption (m³)",
    chartSeriesAmount: "Amount (€)",
    chartAxisKwh: "kWh",
    chartAxisM3: "m³",
    chartAxisAmount: "€",
  },
  energyBill: {
    eyebrow: "Electricity bill",
    fallbackTitle: "Bill",
    summaryTitle: "Summary",
    contractTitle: "Contract",
    costTitle: "Breakdown",
    costEmpty: "No cost lines associated.",
    costCategoryFallback: "Category",
    contractLabels: {
      tariff: "Tariff",
      contract: "Contract",
      cups: "CUPS",
      distributor: "Distributor",
      gridToll: "Grid toll",
    },
  },
  waterBill: {
    eyebrow: "Water bill",
    fallbackTitle: "Bill",
    summaryTitle: "Summary",
    contractTitle: "Contract",
    costTitle: "Breakdown",
    costEmpty: "No cost lines associated.",
    costCategoryFallback: "Category",
    extraLabels: {
      type: "Type",
      status: "Status",
      totalToPay: "Total to pay",
      cancels: "Cancels",
    },
    contractLabels: {
      contract: "Contract",
      meter: "Meter",
      usage: "Usage",
      supplyType: "Supply type",
    },
  },
  gasBill: {
    eyebrow: "Gas bill",
    fallbackTitle: "Bill",
    summaryTitle: "Summary",
    contractTitle: "Supply",
    costTitle: "Breakdown",
    costEmpty: "No cost lines associated.",
    costCategoryFallback: "Category",
    extraLabels: {
      totalToPay: "Total to pay",
      mandateReference: "Mandate reference",
      conversionFactor: "Conversion factor",
      supplyPressure: "Supply pressure",
      peajes: "Tolls",
      cargos: "Charges",
      cnmc: "CNMC",
      gts: "GTS",
      readingPrev: "Previous reading",
      readingCurr: "Current reading",
    },
    contractLabels: {
      accessTariff: "Access tariff",
      commercialTariff: "Commercial tariff",
      contract: "Contract",
      cups: "CUPS",
      meter: "Meter",
      address: "Address",
    },
  },
  bills: {
    countLabel: { singular: "bill", plural: "bills" },
    sortLabels: {
      date: "Date",
      invoice: "Invoice",
      provider: "Provider",
      total: "Total",
      consumption: "Consumption",
    },
    filters: {
      provider: "Provider",
      year: "Year",
      all: "All",
    },
    headers: {
      detail: "Detail",
      type: "Type",
      period: "Period",
      totalToPay: "Total to pay",
      pdf: "PDF",
      cancels: "Cancels",
    },
    pdfPending: "Pending upload",
    invoiceFallback: "Invoice",
  },
  billSummary: {
    provider: "Provider",
    totalAmount: "Total amount",
    consumption: "Consumption",
    issueDate: "Issue date",
    paymentDate: "Charge date",
    pdf: "PDF",
    openFile: "Open file",
  },
  billTypes: {
    factura_regular: "Regular",
    factura_sustitutiva: "Replacement",
    factura_anulacion: "Cancellation",
  },
  tableShell: {
    resultsLabel: { singular: "result", plural: "results" },
    noResults: "No results.",
  },
  maintenanceList: {
    countLabel: { singular: "maintenance", plural: "maintenances" },
  },
  maintenanceTable: {
    sortLabels: {
      date: "Date",
      title: "Maintenance",
      workshop: "Workshop",
      cost: "Cost",
      odometer: "KM",
    },
    filters: {
      workshop: "Workshop",
      year: "Year",
      all: "All",
    },
    headers: {
      summary: "Summary",
      detail: "Detail",
    },
    summary: {
      jobPrefix: "Job",
      partsPrefix: "Parts",
      totals: "Detailed amounts",
    },
  },
  vehicleDetail: {
    eyebrow: "Vehicle",
    noPlate: "No plate registered",
    sheetTitle: "Record",
    summaryTitle: "Summary",
    notesTitle: "Notes",
    maintenanceHistoryTitle: "Maintenance history",
    emptyMaintenances: "No maintenance records yet.",
    labels: {
      brand: "Brand",
      model: "Model",
      year: "Year",
      plate: "Plate",
      vin: "VIN",
      maintenances: "Maintenance",
      lastService: "Last service",
      lastOdometer: "Last odometer",
      lastCost: "Last cost",
    },
  },
  maintenanceDetail: {
    eyebrow: "Maintenance",
    actionBack: "Back to vehicle",
    detailTitle: "Detail",
    vehicleTitle: "Vehicle",
    workDetailTitle: "Work details",
    labels: {
      date: "Date",
      workshop: "Workshop",
      odometer: "Odometer",
      cost: "Cost",
    },
    sections: {
      jobs: "Jobs",
      parts: "Parts",
      totals: "Totals",
    },
    table: {
      concept: "Item",
      amount: "Amount",
    },
  },
  vehiclesList: {
    countLabel: { singular: "vehicle", plural: "vehicles" },
  },
  button: {
    loading: "Loading",
  },
  units: {
    kwh: "kWh",
    m3: "m³",
    km: "km",
    eur: "€",
  },
} as const;
