export const labels = {
  meta: {
    title: "Home Manager",
    description: "Home management control panel.",
  },
  common: {
    panelActiveLabel: "active panel",
    homesActiveLabel: "active homes",
    vehiclesActiveLabel: "active vehicles",
    backToHome: "Back to home",
    backToPanel: "Back to panel",
    backToSelector: "Back to selector",
    backToList: "Back to list",
    backToVehicle: "Back to vehicle",
    open: "Open",
    view: "View",
    viewDetail: "View details",
    openPanel: "Open panel",
    viewBills: "View bills",
    soon: "Coming soon",
    emptyValue: "-",
    noExtraDetails: "No extra details",
    noAdditionalDetails: "No additional details.",
    languageLabel: "Language",
    languageOptions: {
      es: "Spanish",
      en: "English",
    },
    themeToggleLabel: "Theme",
    themeToggleLight: "Switch to light mode",
    themeToggleDark: "Switch to dark mode",
  },
  dashboard: {
    eyebrow: "Control panel",
    title: "Household overview",
    description: "Check reminders, homes, and vehicles from a single hub.",
    panelCode: "HM",
    ticktickProjectsLink: "TickTick projects",
    homeRemindersEyebrow: "Reminders",
    homeRemindersTitle: "Combined reminders",
    homeRemindersDescription:
      "Recent overdue, due today, and upcoming 7-day reminders for vehicles.",
    homeRemindersMissingToken: "Set TICKTICK_ACCESS_TOKEN to load reminders.",
    homeRemindersMissingProject: "No TickTick projects linked to vehicles.",
    homeRemindersError: "Reminders could not be loaded.",
    homeRemindersEmpty: "No reminders in the configured ranges.",
    homeRemindersBucketEmpty: "No reminders in this range.",
    homeRemindersBuckets: {
      overdueWeek: {
        title: "Overdue 7 days",
        description: "Pending from the last week",
      },
      today: {
        title: "Today",
        description: "Pending today",
      },
      upcomingWeek: {
        title: "Upcoming 7 days",
        description: "Due within the next 7 days",
      },
    },
    homesSectionTitle: "Homes",
    homesCardTitle: "Home selector",
    homesCardDescription: "Access each home's panel with bills, consumption, and pending tasks.",
    homesLinkLabel: "View homes",
    vehiclesSectionTitle: "Vehicles",
    vehiclesCardTitle: "Maintenance control",
    vehiclesCardDescription: "Check your cars, workshops, and expenses in one place.",
    vehiclesLinkLabel: "View vehicles",
  },
  ticktickProjects: {
    eyebrow: "TickTick",
    title: "Available projects",
    description: "Internal list to configure project IDs.",
    countLabel: {
      singular: "project",
      plural: "projects",
    },
    tableHeaders: {
      name: "Project",
      id: "ID",
      status: "Status",
    },
    statusOpen: "Open",
    statusClosed: "Closed",
    missingTokenTag: "Missing token",
    missingTokenMessage: "Set TICKTICK_ACCESS_TOKEN to load projects.",
    errorTag: "Unavailable",
    errorMessage: "Projects could not be loaded.",
    emptyMessage: "No projects available.",
    hintMessage: "Copy the ID and use it in TICKTICK_INBOX_PROJECT_ID.",
  },
  homes: {
    eyebrow: "Homes",
    title: "Select your home to manage your household",
    description:
      "See bills, consumption, and tasks in one place. Each home has its own control space.",
    selectorTitle: "Home selector",
    cardBadge: "Home",
    cardDescription: "Direct access to bills, consumption, and maintenance.",
  },
  homeDetail: {
    eyebrow: "Home",
    description: "Quick access to the home's main sections.",
    servicesTitle: "Main services",
    tiles: {
      energy: {
        title: "Electricity",
        description: "Bills and electricity consumption.",
        action: "Open",
      },
      water: {
        title: "Water",
        description: "Bills and consumption tracking.",
        action: "Open",
      },
      gas: {
        title: "Gas",
        description: "Gas billing and consumption.",
        action: "Open",
      },
      insurance: {
        title: "Insurance",
        description: "Policies and renewals.",
        action: "Coming soon",
      },
    },
  },
  vehicles: {
    eyebrow: "Vehicles",
    title: "Manage your household fleet",
    description: "View records and recent maintenance for each car.",
    listTitle: "Registered vehicles",
    emptyList: "No vehicles registered yet.",
    cardBadge: "Vehicle",
    statLabel: "maintenance",
    defaultIcon: "V",
  },
  fuelPrices: {
    title: "Fuel prices",
    description: "Check updated prices by postal code.",
    postalCodeLabel: "Postal code",
    postalCodePlaceholder: "28880",
    postalCodeHelp: "Enter 5 digits to search nearby stations.",
    postalCodeInvalid: "Postal code must be 5 digits.",
    fuelLabel: "Fuel",
    fuels: {
      dieselA: "Diesel A",
      dieselAPremium: "Diesel A Premium",
      gas95: "Gasoline 95 E5",
      gas98: "Gasoline 98 E5",
    },
    fuelSelectionInvalid: "Select at least one fuel.",
    favoriteAction: "Save favorite",
    favoriteListLabel: "Favorites",
    favoriteModalTitle: "Save postal code",
    favoriteModalDescription: "Give this postal code a name.",
    favoriteNameLabel: "Name",
    favoriteNamePlaceholder: "Example: Home",
    favoriteNameInvalid: "Enter a name for the favorite.",
    favoriteSave: "Save",
    favoriteCancel: "Cancel",
    favoriteRemove: "Remove",
    favoriteRemoveLabel: "Remove favorite",
    searchAction: "Search",
    loadingAction: "Searching",
    emptyList: "No stations found for that postal code.",
    fetchError: "Unable to load prices right now.",
    countLabel: { singular: "station", plural: "stations" },
    updatedLabel: "Updated",
    priceUnit: "€/L",
    priceUnavailable: "No price",
    unknownStation: "Unknown station",
    addressFallback: "Address unavailable",
  },
  energy: {
    eyebrow: "Electricity",
    titlePrefix: "Bills for",
    description: "Review electricity billing amounts and periods.",
    listTitle: "Bill list",
    emptyList: "No bills registered yet.",
    chartTitle: "Electricity consumption",
    chartSubtitle: "kWh and amount per bill",
    chartEmpty: "No consumption recorded to display.",
    chartSeriesKwh: "Consumption (kWh)",
    chartSeriesAmount: "Amount (€)",
    chartAxisKwh: "kWh",
    chartAxisAmount: "€",
    dailyAverageLabel: "Average cost per day (filtered bills)",
    comparison: {
      title: "Yearly comparison",
      description: "Monthly amounts, consumption, and average €/kWh.",
      empty: "Not enough data to compare the selected years.",
      actionLabel: "View comparison",
      deltaLabel: "Difference",
      chartTitle: "Monthly comparison",
      chartSubtitle: "Overlaid lines by year",
      chartMetricLabel: "Metric",
      chartMetricAmount: "Amount",
      chartMetricUsage: "kWh",
      chartAxisAmount: "€",
      chartAxisUsage: "kWh",
      filters: {
        yearA: "Base year",
        yearB: "Compared year",
        apply: "Apply",
      },
      columns: {
        month: "Month",
        amount: "Amount",
        usage: "Consumption",
        eurPerUnit: "€/kWh",
        bill: "Bill",
        deltaAmount: "Δ Amount",
        deltaUsage: "Δ kWh",
      },
    },
  },
  water: {
    eyebrow: "Water",
    titlePrefix: "Bills for",
    description: "Review water billing amounts and periods.",
    listTitle: "Bill list",
    emptyList: "No bills registered yet.",
    chartTitle: "Water consumption",
    chartSubtitle: "m³ and amount per bill",
    chartEmpty: "No consumption recorded to display.",
    chartSeriesM3: "Consumption (m³)",
    chartSeriesAmount: "Amount (€)",
    chartAxisM3: "m³",
    chartAxisAmount: "€",
    totalConsumptionLabel: "Total consumption (filtered bills)",
    dailyConsumptionLabel: "Average daily consumption (filtered bills)",
    dailyAverageLabel: "Average cost per day (filtered bills)",
    comparison: {
      title: "Yearly comparison",
      description: "Monthly amounts, consumption, and average €/m³.",
      empty: "Not enough data to compare the selected years.",
      actionLabel: "View comparison",
      deltaLabel: "Difference",
      chartTitle: "Monthly comparison",
      chartSubtitle: "Overlaid lines by year",
      chartMetricLabel: "Metric",
      chartMetricAmount: "Amount",
      chartMetricUsage: "m³",
      chartAxisAmount: "€",
      chartAxisUsage: "m³",
      filters: {
        yearA: "Base year",
        yearB: "Compared year",
        apply: "Apply",
      },
      columns: {
        month: "Month",
        amount: "Amount",
        usage: "Consumption",
        eurPerUnit: "€/m³",
        bill: "Bill",
        deltaAmount: "Δ Amount",
        deltaUsage: "Δ m³",
      },
    },
  },
  gas: {
    eyebrow: "Gas",
    titlePrefix: "Bills for",
    description: "Review gas billing amounts and periods.",
    listTitle: "Bill list",
    emptyList: "No bills registered yet.",
    boilerActionLabel: "Boiler details",
    chartTitle: "Gas consumption",
    chartSubtitle: "kWh and m³ per bill",
    chartEmpty: "No consumption recorded to display.",
    chartSeriesKwh: "Consumption (kWh)",
    chartSeriesM3: "Consumption (m³)",
    chartSeriesAmount: "Amount (€)",
    chartAxisKwh: "kWh",
    chartAxisM3: "m³",
    chartAxisAmount: "€",
    dailyAverageLabel: "Average cost per day (filtered bills)",
    comparison: {
      title: "Yearly comparison",
      description: "Monthly amounts, consumption, and average €/kWh.",
      empty: "Not enough data to compare the selected years.",
      actionLabel: "View comparison",
      deltaLabel: "Difference",
      chartTitle: "Monthly comparison",
      chartSubtitle: "Overlaid lines by year",
      chartMetricLabel: "Metric",
      chartMetricAmount: "Amount",
      chartMetricUsage: "kWh",
      chartAxisAmount: "€",
      chartAxisUsage: "kWh",
      filters: {
        yearA: "Base year",
        yearB: "Compared year",
        apply: "Apply",
      },
      columns: {
        month: "Month",
        amount: "Amount",
        usage: "Consumption",
        eurPerUnit: "€/kWh",
        bill: "Bill",
        deltaAmount: "Δ Amount",
        deltaUsage: "Δ kWh",
      },
    },
  },
  gasBoiler: {
    eyebrow: "Gas",
    titlePrefix: "Boiler for",
    description: "Boiler details and maintenance.",
    emptyMessage: "No boiler details have been registered yet.",
    equipmentTitle: "Equipment",
    maintenanceTitle: "Maintenance",
    maintenanceHistoryTitle: "Maintenance history",
    maintenanceHistoryEmpty: "No events registered yet.",
    labels: {
      installation: "Installation",
      commissioningDate: "Commissioning date",
      officialServiceCompany: "Official service company",
      lastAnnualReview: "Last annual review",
      maintenancePlan: "Maintenance plan",
      contractNumber: "Contract number",
      contractStart: "Start date",
      contractEnd: "Valid until",
    },
    eventLabels: {
      date: "Date",
      provider: "Provider",
      amount: "Amount",
      paymentMethod: "Payment method",
      expiresOn: "Expires",
      notes: "Notes",
      coverage: "Coverage",
    },
  },
  energyBill: {
    eyebrow: "Electricity bill",
    fallbackTitle: "Bill",
    summaryTitle: "Summary",
    contractTitle: "Contract",
    costTitle: "Breakdown",
    costEmpty: "No cost lines associated.",
    costCategoryFallback: "Category",
    contractLabels: {
      tariff: "Tariff",
      contract: "Contract",
      cups: "CUPS",
      distributor: "Distributor",
      gridToll: "Grid toll",
    },
  },
  waterBill: {
    eyebrow: "Water bill",
    fallbackTitle: "Bill",
    summaryTitle: "Summary",
    contractTitle: "Contract",
    costTitle: "Breakdown",
    costEmpty: "No cost lines associated.",
    costCategoryFallback: "Category",
    extraLabels: {
      type: "Type",
      status: "Status",
      totalToPay: "Total to pay",
      cancels: "Cancels",
    },
    contractLabels: {
      contract: "Contract",
      meter: "Meter",
      usage: "Usage",
      supplyType: "Supply type",
    },
  },
  gasBill: {
    eyebrow: "Gas bill",
    fallbackTitle: "Bill",
    summaryTitle: "Summary",
    contractTitle: "Supply",
    costTitle: "Breakdown",
    costEmpty: "No cost lines associated.",
    costCategoryFallback: "Category",
    extraLabels: {
      totalToPay: "Total to pay",
      mandateReference: "Mandate reference",
      conversionFactor: "Conversion factor",
      supplyPressure: "Supply pressure",
      peajes: "Tolls",
      cargos: "Charges",
      cnmc: "CNMC",
      gts: "GTS",
      readingPrev: "Previous reading",
      readingCurr: "Current reading",
    },
    contractLabels: {
      accessTariff: "Access tariff",
      commercialTariff: "Commercial tariff",
      contract: "Contract",
      cups: "CUPS",
      meter: "Meter",
      address: "Address",
    },
  },
  bills: {
    countLabel: { singular: "bill", plural: "bills" },
    sortLabels: {
      date: "Date",
      invoice: "Invoice",
      provider: "Provider",
      total: "Total",
      consumption: "Consumption",
    },
    filters: {
      provider: "Provider",
      year: "Year",
      all: "All",
    },
    headers: {
      detail: "Detail",
      type: "Type",
      period: "Period",
      totalToPay: "Total to pay",
      pdf: "PDF",
      cancels: "Cancels",
    },
    pdfPending: "Pending upload",
    invoiceFallback: "Invoice",
  },
  billSummary: {
    provider: "Provider",
    totalAmount: "Total amount",
    consumption: "Consumption",
    issueDate: "Issue date",
    paymentDate: "Charge date",
    pdf: "PDF",
    openFile: "Open file",
  },
  billTypes: {
    factura_regular: "Regular",
    factura_sustitutiva: "Replacement",
    factura_anulacion: "Cancellation",
  },
  tableShell: {
    resultsLabel: { singular: "result", plural: "results" },
    noResults: "No results.",
  },
  maintenanceList: {
    countLabel: { singular: "maintenance", plural: "maintenances" },
  },
  maintenanceTable: {
    sortLabels: {
      date: "Date",
      title: "Maintenance",
      workshop: "Workshop",
      cost: "Cost",
      odometer: "KM",
    },
    filters: {
      workshop: "Workshop",
      year: "Year",
      all: "All",
    },
    headers: {
      summary: "Summary",
      detail: "Detail",
    },
    summary: {
      jobPrefix: "Job",
      partsPrefix: "Parts",
      totals: "Detailed amounts",
    },
  },
  vehicleDetail: {
    eyebrow: "Vehicle",
    noPlate: "No plate registered",
    sheetTitle: "Record",
    summaryTitle: "Summary",
    notesTitle: "Notes",
    maintenanceHistoryTitle: "Maintenance history",
    emptyMaintenances: "No maintenance records yet.",
    purchaseActionLabel: "See more details",
    remindersEyebrow: "TickTick",
    remindersTitle: "Vehicle reminders",
    remindersDescription: "Tasks from the project linked to this vehicle.",
    remindersProjectsLink: "Projects",
    remindersCountLabel: {
      singular: "reminder",
      plural: "reminders",
    },
    remindersTabs: {
      recent: "Overdue & today",
      upcoming: "Upcoming",
      noDate: "No due date",
      overdueLong: "Overdue > 30 days",
    },
    remindersDueLabel: "due",
    remindersOverdueLabel: "overdue",
    remindersNoDueDate: "No due date",
    remindersEmpty: "No reminders pending.",
    remindersMissingProjectTag: "Missing project",
    remindersMissingProjectMessage: "Set a TickTick project for this vehicle.",
    remindersMissingTokenTag: "Missing token",
    remindersMissingTokenMessage: "Set TICKTICK_ACCESS_TOKEN to load reminders.",
    remindersErrorTag: "Unavailable",
    remindersErrorMessage: "Reminders could not be loaded.",
    labels: {
      brand: "Brand",
      model: "Model",
      year: "Year",
      plate: "Plate",
      vin: "VIN",
      maintenances: "Maintenance",
      lastService: "Last service",
      lastOdometer: "Last odometer",
      lastCost: "Last cost",
      purchaseDate: "Purchase date",
      purchaseTotal: "Total to pay",
      purchaseModel: "Purchase model",
      purchaseDealer: "Dealer",
    },
  },
  vehiclePurchase: {
    eyebrow: "Vehicle",
    title: "Vehicle purchase",
    actionBack: "Back to vehicle",
    emptyState: "No purchase recorded yet.",
    offerTitle: "Offer",
    dealerTitle: "Dealer",
    advisorTitle: "Sales advisor",
    customerTitle: "Customer",
    vehicleTitle: "Vehicle",
    optionsTitle: "Options",
    optionsEmpty: "No options recorded.",
    economicDetailTitle: "Economic detail",
    summaryTitle: "Operation summary",
    labels: {
      issueDate: "Issue date",
      validUntil: "Valid until",
      offerNumber: "Offer number",
      customerNumber: "Customer number",
      dealerName: "Name",
      dealerAddress: "Address",
      dealerPhone: "Phone",
      dealerEmail: "Email",
      advisorName: "Name",
      advisorPhone: "Phone",
      advisorEmail: "Email",
      customerFirstName: "First name",
      customerLastName: "Last name",
      customerPhone: "Phone",
      customerEmail: "Email",
      vehicleModel: "Model",
      vehicleTransmission: "Transmission",
      vehicleTrim: "Trim",
      vehicleFuel: "Fuel",
      vehiclePowerKw: "Power (kW)",
      vehiclePowerCv: "Power (HP)",
      vehicleEmissions: "CO2 WLTP (g/km)",
      optionsTotalBase: "Options base",
      optionsTotalPvp: "Options MSRP",
      servicesTotal: "Services",
      accessoriesTotal: "Accessories",
      vehicleBasePrice: "Vehicle base",
      vehiclePvpPrice: "Vehicle MSRP",
      campaignBase: "Campaign base",
      campaignPvp: "Campaign MSRP",
      vatAmount: "VAT",
      registrationTaxAmount: "Registration tax",
      taxDeduction: "Tax deduction",
      vehicleSubtotalBase: "Subtotal base",
      vehicleSubtotalPvp: "Subtotal MSRP",
      summaryServices: "Services",
      summaryAccessories: "Accessories",
      summarySupplies: "Supplies",
      totalWithoutTradeIn: "Total without trade-in",
      tradeInValue: "Trade-in value",
      totalToPay: "Total to pay",
      optionDescription: "Option",
      optionBasePrice: "Base",
      optionPvpPrice: "MSRP",
    },
  },
  maintenanceDetail: {
    eyebrow: "Maintenance",
    actionBack: "Back to vehicle",
    detailTitle: "Detail",
    vehicleTitle: "Vehicle",
    workDetailTitle: "Work details",
    labels: {
      date: "Date",
      workshop: "Workshop",
      odometer: "Odometer",
      cost: "Cost",
    },
    sections: {
      jobs: "Jobs",
      parts: "Parts",
      totals: "Totals",
    },
    table: {
      concept: "Item",
      amount: "Amount",
    },
  },
  vehiclesList: {
    countLabel: { singular: "vehicle", plural: "vehicles" },
  },
  button: {
    loading: "Loading",
  },
  units: {
    kwh: "kWh",
    m3: "m³",
    km: "km",
    eur: "€",
    liters: "L",
  },
} as const;
