export const labels = {
  meta: {
    title: "Home Manager",
    description: "Panel de control para la gestión del hogar.",
  },
  common: {
    panelActiveLabel: "panel activo",
    homesActiveLabel: "viviendas activas",
    vehiclesActiveLabel: "vehículos activos",
    backToHome: "Volver al inicio",
    backToPanel: "Volver al panel",
    backToSelector: "Volver al selector",
    backToList: "Volver al listado",
    backToVehicle: "Volver al vehículo",
    open: "Abrir",
    view: "Ver",
    viewDetail: "Ver detalle",
    openPanel: "Abrir panel",
    viewBills: "Ver facturas",
    soon: "Próximamente",
    emptyValue: "-",
    yesLabel: "Sí",
    noLabel: "No",
    noExtraDetails: "Sin detalles extra",
    noAdditionalDetails: "Sin detalles adicionales.",
    languageLabel: "Idioma",
    languageOptions: {
      es: "Español",
      en: "Inglés",
    },
    themeToggleLabel: "Tema",
    themeToggleLight: "Activar modo claro",
    themeToggleDark: "Activar modo oscuro",
  },
  dashboard: {
    eyebrow: "Panel de control",
    title: "Panel general del hogar",
    description: "Consulta recordatorios, viviendas y vehículos desde un único punto.",
    panelCode: "HM",
    ticktickProjectsLink: "Proyectos TickTick",
    homeRemindersEyebrow: "Recordatorios",
    homeRemindersTitle: "Recordatorios combinados",
    homeRemindersDescription:
      "Vencidos recientes, pendientes de hoy y próximos 7 días de los vehículos.",
    homeRemindersMissingToken: "Configura TICKTICK_ACCESS_TOKEN para ver recordatorios.",
    homeRemindersMissingProject: "No hay proyectos TickTick asociados a vehículos.",
    homeRemindersError: "No se han podido cargar los recordatorios.",
    homeRemindersEmpty: "No hay recordatorios en los rangos configurados.",
    homeRemindersBucketEmpty: "Sin recordatorios en este rango.",
    homeRemindersBuckets: {
      overdueWeek: {
        title: "Vencidas 7 días",
        description: "Pendientes de la última semana",
      },
      today: {
        title: "Hoy",
        description: "Pendientes para hoy",
      },
      upcomingWeek: {
        title: "Próximos 7 días",
        description: "Vencen en los próximos 7 días",
      },
    },
    homesSectionTitle: "Viviendas",
    homesCardTitle: "Selector de viviendas",
    homesCardDescription: "Accede al panel de cada casa con facturas, consumo y tareas pendientes.",
    homesLinkLabel: "Ver viviendas",
    vehiclesSectionTitle: "Vehículos",
    vehiclesCardTitle: "Control de mantenimiento",
    vehiclesCardDescription: "Consulta tus coches, talleres y gastos en un solo lugar.",
    vehiclesLinkLabel: "Ver vehículos",
  },
  ticktickProjects: {
    eyebrow: "TickTick",
    title: "Proyectos disponibles",
    description: "Listado interno para configurar IDs de proyectos.",
    countLabel: {
      singular: "proyecto",
      plural: "proyectos",
    },
    tableHeaders: {
      name: "Proyecto",
      id: "ID",
      status: "Estado",
    },
    statusOpen: "Abierto",
    statusClosed: "Cerrado",
    missingTokenTag: "Falta token",
    missingTokenMessage: "Configura TICKTICK_ACCESS_TOKEN para ver proyectos.",
    errorTag: "Sin acceso",
    errorMessage: "No se han podido cargar los proyectos.",
    emptyMessage: "No hay proyectos disponibles.",
    hintMessage: "Copia el ID y úsalo en TICKTICK_INBOX_PROJECT_ID.",
  },
  homes: {
    eyebrow: "Viviendas",
    title: "Selecciona tu vivienda para gestionar tu hogar",
    description:
      "Visualiza facturas, consumo y tareas en un solo lugar. Cada vivienda tiene su propio espacio de control.",
    selectorTitle: "Selector de viviendas",
    cardBadge: "Vivienda",
    cardDescription: "Acceso directo a facturas, consumo y mantenimientos.",
  },
  homeDetail: {
    eyebrow: "Vivienda",
    description: "Accesos rápidos a los apartados principales de la vivienda.",
    servicesTitle: "Servicios principales",
    tiles: {
      energy: {
        title: "Luz",
        description: "Facturas y consumo eléctrico.",
        action: "Abrir",
      },
      water: {
        title: "Agua",
        description: "Recibos y seguimiento del consumo.",
        action: "Abrir",
      },
      gas: {
        title: "Gas",
        description: "Facturación y consumo de gas.",
        action: "Abrir",
      },
      insurance: {
        title: "Seguros",
        description: "Pólizas y vencimientos.",
        action: "Abrir",
      },
    },
  },
  homeInsurance: {
    eyebrow: "Seguro",
    titlePrefix: "Seguro de",
    description: "Resumen y renovaciones de la póliza del hogar.",
    listTitle: "Renovaciones registradas",
    emptyList: "Todavía no hay pólizas registradas.",
    coveragesTitle: "Coberturas",
    receiptTitle: "Recibo",
    paymentTitle: "Pago",
    loyaltyTitle: "Club Mapfre",
    documentLinkLabel: "Abrir documento",
    fields: {
      insurer: "Aseguradora",
      product: "Producto",
      policyNumber: "Número de póliza",
      documentStatus: "Estado del documento",
      issueDate: "Fecha de emisión",
      effectiveDate: "Inicio de vigencia",
      expiryDate: "Fin de vigencia",
      receiptPeriod: "Período de recibo",
      revaluationPct: "Revalorización",
      premiumTotal: "Importe total",
      paymentMethod: "Forma de pago",
      paymentFrequency: "Periodicidad",
      riskAddress: "Riesgo asegurado",
      documentUrl: "Documento",
    },
    coverages: {
      dwelling: "Vivienda",
      contents: "Mobiliario",
      jewelry: "Joyas",
      aestheticDwelling: "Daños estéticos vivienda",
      aestheticContents: "Daños estéticos mobiliario",
      liability: "Responsabilidad civil",
      legalDefense: "Defensa jurídica",
    },
    receipt: {
      basePremium: "Prima tarifa",
      legalDefense: "Prima defensa jurídica",
      consortium: "Consorcio",
      taxes: "Impuestos",
      total: "Total recibo",
    },
    payment: {
      cardMasked: "Tarjeta",
    },
    loyalty: {
      treboles: "Tréboles acumulados",
      conversion: "Conversión",
      minimumDiscount: "Mínimo descuento",
    },
  },
  vehicles: {
    eyebrow: "Vehículos",
    title: "Gestiona tu flota doméstica",
    description: "Consulta fichas y mantenimientos recientes de cada coche.",
    listTitle: "Vehículos registrados",
    emptyList: "Todavía no hay vehículos registrados.",
    cardBadge: "Vehículo",
    statLabel: "mantenimientos",
    defaultIcon: "V",
  },
  fuelPrices: {
    title: "Precios de gasolina",
    description: "Consulta precios actualizados por código postal.",
    postalCodeLabel: "Código postal",
    postalCodePlaceholder: "28880",
    postalCodeHelp: "Introduce 5 dígitos para buscar estaciones cercanas.",
    postalCodeInvalid: "El código postal debe tener 5 dígitos.",
    fuelLabel: "Combustible",
    fuels: {
      dieselA: "Gasóleo A",
      dieselAPremium: "Gasóleo A Premium",
      gas95: "Gasolina 95 E5",
      gas98: "Gasolina 98 E5",
    },
    fuelSelectionInvalid: "Selecciona al menos un combustible.",
    favoriteAction: "Guardar favorito",
    favoriteListLabel: "Favoritos",
    favoriteModalTitle: "Guardar código postal",
    favoriteModalDescription: "Asigna un nombre para este código postal.",
    favoriteNameLabel: "Nombre",
    favoriteNamePlaceholder: "Ejemplo: Casa",
    favoriteNameInvalid: "Escribe un nombre para el favorito.",
    favoriteSave: "Guardar",
    favoriteCancel: "Cancelar",
    favoriteRemove: "Quitar",
    favoriteRemoveLabel: "Eliminar favorito",
    searchAction: "Buscar",
    loadingAction: "Buscando",
    emptyList: "No hay estaciones para ese código postal.",
    fetchError: "No se han podido cargar los precios ahora mismo.",
    countLabel: { singular: "estación", plural: "estaciones" },
    updatedLabel: "Actualizado",
    priceUnit: "€/L",
    priceUnavailable: "Sin precio",
    unknownStation: "Estación sin rótulo",
    addressFallback: "Dirección no disponible",
  },
  energy: {
    eyebrow: "Luz",
    titlePrefix: "Facturas de",
    description: "Revisa los importes y períodos de facturación de electricidad.",
    listTitle: "Listado de facturas",
    emptyList: "Todavía no hay facturas registradas.",
    chartTitle: "Consumo eléctrico",
    chartSubtitle: "kWh e importe por factura",
    chartEmpty: "No hay consumo registrado para representar.",
    chartSeriesKwh: "Consumo (kWh)",
    chartSeriesAmount: "Importe (€)",
    chartAxisKwh: "kWh",
    chartAxisAmount: "€",
    dailyAverageLabel: "Gasto medio por día (facturas filtradas)",
    comparison: {
      title: "Comparativa anual",
      description: "Importes, consumo y coste medio por kWh mes a mes.",
      empty: "No hay datos suficientes para comparar los años seleccionados.",
      actionLabel: "Ver comparativa",
      deltaLabel: "Diferencia",
      chartTitle: "Comparativa mensual",
      chartSubtitle: "Líneas superpuestas por año",
      chartMetricLabel: "Métrica",
      chartMetricAmount: "Importe",
      chartMetricUsage: "kWh",
      chartAxisAmount: "€",
      chartAxisUsage: "kWh",
      filters: {
        yearA: "Año base",
        yearB: "Año comparado",
        apply: "Aplicar",
      },
      columns: {
        month: "Mes",
        amount: "Importe",
        usage: "Consumo",
        eurPerUnit: "€/kWh",
        bill: "Factura",
        deltaAmount: "Δ Importe",
        deltaUsage: "Δ kWh",
      },
    },
  },
  water: {
    eyebrow: "Agua",
    titlePrefix: "Facturas de",
    description: "Revisa los importes y períodos de facturación de agua.",
    listTitle: "Listado de facturas",
    emptyList: "Todavía no hay facturas registradas.",
    chartTitle: "Consumo de agua",
    chartSubtitle: "m³ e importe por factura",
    chartEmpty: "No hay consumo registrado para representar.",
    chartSeriesM3: "Consumo (m³)",
    chartSeriesAmount: "Importe (€)",
    chartAxisM3: "m³",
    chartAxisAmount: "€",
    totalConsumptionLabel: "Consumo total (facturas filtradas)",
    dailyConsumptionLabel: "Consumo medio por día (facturas filtradas)",
    dailyAverageLabel: "Gasto medio por día (facturas filtradas)",
    comparison: {
      title: "Comparativa anual",
      description: "Importes, consumo y coste medio por m³ mes a mes.",
      empty: "No hay datos suficientes para comparar los años seleccionados.",
      actionLabel: "Ver comparativa",
      deltaLabel: "Diferencia",
      chartTitle: "Comparativa mensual",
      chartSubtitle: "Líneas superpuestas por año",
      chartMetricLabel: "Métrica",
      chartMetricAmount: "Importe",
      chartMetricUsage: "m³",
      chartAxisAmount: "€",
      chartAxisUsage: "m³",
      filters: {
        yearA: "Año base",
        yearB: "Año comparado",
        apply: "Aplicar",
      },
      columns: {
        month: "Mes",
        amount: "Importe",
        usage: "Consumo",
        eurPerUnit: "€/m³",
        bill: "Factura",
        deltaAmount: "Δ Importe",
        deltaUsage: "Δ m³",
      },
    },
  },
  gas: {
    eyebrow: "Gas",
    titlePrefix: "Facturas de",
    description: "Revisa los importes y períodos de facturación de gas.",
    listTitle: "Listado de facturas",
    emptyList: "Todavía no hay facturas registradas.",
    boilerActionLabel: "Ficha caldera",
    chartTitle: "Consumo de gas",
    chartSubtitle: "kWh y m³ por factura",
    chartEmpty: "No hay consumo registrado para representar.",
    chartSeriesKwh: "Consumo (kWh)",
    chartSeriesM3: "Consumo (m³)",
    chartSeriesAmount: "Importe (€)",
    chartAxisKwh: "kWh",
    chartAxisM3: "m³",
    chartAxisAmount: "€",
    dailyAverageLabel: "Gasto medio por día (facturas filtradas)",
    comparison: {
      title: "Comparativa anual",
      description: "Importes, consumo y coste medio por kWh mes a mes.",
      empty: "No hay datos suficientes para comparar los años seleccionados.",
      actionLabel: "Ver comparativa",
      deltaLabel: "Diferencia",
      chartTitle: "Comparativa mensual",
      chartSubtitle: "Líneas superpuestas por año",
      chartMetricLabel: "Métrica",
      chartMetricAmount: "Importe",
      chartMetricUsage: "kWh",
      chartAxisAmount: "€",
      chartAxisUsage: "kWh",
      filters: {
        yearA: "Año base",
        yearB: "Año comparado",
        apply: "Aplicar",
      },
      columns: {
        month: "Mes",
        amount: "Importe",
        usage: "Consumo",
        eurPerUnit: "€/kWh",
        bill: "Factura",
        deltaAmount: "Δ Importe",
        deltaUsage: "Δ kWh",
      },
    },
  },
  gasBoiler: {
    eyebrow: "Gas",
    titlePrefix: "Caldera de",
    description: "Detalles de la caldera y mantenimiento.",
    emptyMessage: "Todavía no hay datos de la caldera registrados.",
    equipmentTitle: "Equipo",
    maintenanceTitle: "Mantenimiento",
    maintenanceHistoryTitle: "Historial de mantenimiento",
    maintenanceHistoryEmpty: "Todavía no hay eventos registrados.",
    labels: {
      installation: "Mi instalación",
      commissioningDate: "Puesta en marcha",
      officialServiceCompany: "Servicio técnico oficial",
      lastAnnualReview: "Última revisión anual",
      maintenancePlan: "Servicio contratado",
      contractNumber: "Número contrato",
      contractStart: "Fecha alta",
      contractEnd: "Contrato válido hasta",
    },
    eventLabels: {
      date: "Fecha",
      provider: "Proveedor",
      amount: "Importe",
      paymentMethod: "Forma de pago",
      expiresOn: "Vencimiento",
      notes: "Notas",
      coverage: "Cobertura",
    },
  },
  energyBill: {
    eyebrow: "Factura de luz",
    fallbackTitle: "Factura",
    summaryTitle: "Resumen",
    contractTitle: "Contrato",
    costTitle: "Desglose",
    costEmpty: "No hay líneas de coste asociadas.",
    costCategoryFallback: "Categoría",
    contractLabels: {
      tariff: "Tarifa",
      contract: "Contrato",
      cups: "CUPS",
      distributor: "Distribuidora",
      gridToll: "Peaje",
    },
  },
  waterBill: {
    eyebrow: "Factura de agua",
    fallbackTitle: "Factura",
    summaryTitle: "Resumen",
    contractTitle: "Contrato",
    costTitle: "Desglose",
    costEmpty: "No hay líneas de coste asociadas.",
    costCategoryFallback: "Categoría",
    extraLabels: {
      type: "Tipo",
      status: "Estado",
      totalToPay: "Total a pagar",
      cancels: "Anula",
    },
    contractLabels: {
      contract: "Contrato",
      meter: "Contador",
      usage: "Uso",
      supplyType: "Tipo suministro",
    },
  },
  gasBill: {
    eyebrow: "Factura de gas",
    fallbackTitle: "Factura",
    summaryTitle: "Resumen",
    contractTitle: "Suministro",
    costTitle: "Desglose",
    costEmpty: "No hay líneas de coste asociadas.",
    costCategoryFallback: "Categoría",
    extraLabels: {
      totalToPay: "Total a pagar",
      mandateReference: "Referencia mandato",
      conversionFactor: "Factor conversión",
      supplyPressure: "Presión suministro",
      peajes: "Peajes",
      cargos: "Cargos",
      cnmc: "CNMC",
      gts: "GTS",
      readingPrev: "Lectura anterior",
      readingCurr: "Lectura actual",
    },
    contractLabels: {
      accessTariff: "Tarifa acceso",
      commercialTariff: "Tarifa comercial",
      contract: "Contrato",
      cups: "CUPS",
      meter: "Contador",
      address: "Dirección",
    },
  },
  bills: {
    countLabel: { singular: "factura", plural: "facturas" },
    sortLabels: {
      date: "Fecha",
      invoice: "Factura",
      provider: "Proveedor",
      total: "Total",
      consumption: "Consumo",
    },
    filters: {
      provider: "Proveedor",
      year: "Año",
      all: "Todos",
    },
    headers: {
      detail: "Detalle",
      type: "Tipo",
      period: "Periodo",
      totalToPay: "Total a pagar",
      pdf: "PDF",
      cancels: "Anula",
    },
    pdfPending: "Pendiente de subir",
    invoiceFallback: "Factura",
  },
  billSummary: {
    provider: "Proveedor",
    totalAmount: "Importe total",
    consumption: "Consumo",
    issueDate: "Fecha de emisión",
    paymentDate: "Fecha de cargo",
    pdf: "PDF",
    openFile: "Abrir archivo",
  },
  billTypes: {
    factura_regular: "Regular",
    factura_sustitutiva: "Sustitutiva",
    factura_anulacion: "Anulación",
  },
  tableShell: {
    resultsLabel: { singular: "resultado", plural: "resultados" },
    noResults: "Sin resultados.",
  },
  maintenanceList: {
    countLabel: { singular: "mantenimiento", plural: "mantenimientos" },
  },
  maintenanceTable: {
    sortLabels: {
      date: "Fecha",
      title: "Mantenimiento",
      workshop: "Taller",
      cost: "Coste",
      odometer: "KM",
    },
    filters: {
      workshop: "Taller",
      year: "Año",
      all: "Todos",
    },
    headers: {
      summary: "Resumen",
      detail: "Detalle",
    },
    summary: {
      jobPrefix: "Trabajo",
      partsPrefix: "Piezas",
      totals: "Importes detallados",
    },
  },
  vehicleDetail: {
    eyebrow: "Vehículo",
    noPlate: "Sin matrícula registrada",
    sheetTitle: "Ficha",
    summaryTitle: "Resumen",
    specsTitle: "Ficha técnica",
    registrationTitle: "Documento de circulación",
    insuranceTitle: "Seguro",
    insuranceEmpty: "Todavía no hay seguro registrado.",
    insuranceActionLabel: "Ver seguro",
    notesTitle: "Notas",
    maintenanceHistoryTitle: "Historial de mantenimientos",
    maintenanceHistoryActionLabel: "Ver mantenimientos",
    emptyMaintenances: "Todavía no hay mantenimientos registrados.",
    purchaseActionLabel: "Ver más detalles",
    remindersEyebrow: "TickTick",
    remindersTitle: "Recordatorios del vehículo",
    remindersDescription: "Tareas del proyecto asociado a este vehículo.",
    remindersProjectsLink: "Proyectos",
    remindersCountLabel: {
      singular: "recordatorio",
      plural: "recordatorios",
    },
    remindersTabs: {
      recent: "Vencidas y hoy",
      upcoming: "Próximas",
      noDate: "Sin fecha",
      overdueLong: "Vencidas > 30 días",
    },
    remindersDueLabel: "vence",
    remindersOverdueLabel: "vencida",
    remindersNoDueDate: "Sin fecha",
    remindersEmpty: "No hay recordatorios pendientes.",
    remindersMissingProjectTag: "Sin proyecto",
    remindersMissingProjectMessage: "Configura el proyecto TickTick del vehículo.",
    remindersMissingTokenTag: "Falta token",
    remindersMissingTokenMessage: "Configura TICKTICK_ACCESS_TOKEN para ver recordatorios.",
    remindersErrorTag: "Sin acceso",
    remindersErrorMessage: "No se han podido cargar los recordatorios.",
    labels: {
      brand: "Marca",
      model: "Modelo",
      year: "Año",
      plate: "Matrícula",
      vin: "VIN",
      maintenances: "Mantenimientos",
      lastService: "Último servicio",
      lastOdometer: "Último odómetro",
      lastCost: "Último coste",
      purchaseDate: "Fecha de compra",
      purchaseTotal: "Total a pagar",
      purchaseModel: "Modelo compra",
      purchaseDealer: "Concesionario",
    },
    specsLabels: {
      tireSpec: "Neumático (completo)",
      tireSize: "Neumático (medida)",
      tireLoadIndex: "Índice de carga",
      tireSpeedIndex: "Código de velocidad",
      type: "Tipo",
      fuel: "Combustible",
      engineDisplacement: "Cilindrada",
      powerNet: "Potencia neta",
      emissionsCo2: "CO₂",
      emissionsStandard: "Norma emisiones",
      seats: "Plazas",
      color: "Color",
      service: "Servicio",
      maxMass: "Masa máxima",
      maxLoad: "Masa máxima carga",
      massInService: "Masa en circulación",
      powerWeightRatio: "Relación potencia/peso",
      homologationCode: "Contraseña homologación",
      homologationCodeBase: "Homologación base",
      baseBrand: "Marca base",
      baseType: "Tipo base",
      variant: "Variante",
      version: "Versión",
    },
    registrationLabels: {
      documentType: "Tipo documento",
      documentReference: "Referencia",
      caseFileNumber: "Expediente",
      issueDate: "Fecha expedición",
      documentDate: "Fecha documento",
      validUntil: "Válido hasta",
      verificationCode: "CSV",
      verificationLink: "Validar",
      issuingAuthority: "Organismo",
      issuingMinistry: "Ministerio",
      documentModel: "Modelo documento",
      registrationOffice: "Jefatura",
      originCode: "Procedencia",
      additionalCode: "Código adicional",
      documentHash: "Hash documento",
      holderName: "Titular",
      holderIsRenting: "Renting",
      validityDays: "Validez (días)",
      requiresValidInspection: "Requiere ITV vigente",
      invalidForAdministrativeProcedures: "No válido para trámites",
    },
    insuranceLabels: {
      insurer: "Aseguradora",
      policyNumber: "Póliza",
      policyType: "Tipo",
      effectiveDate: "Fecha efecto",
      expiryDate: "Vencimiento",
      premiumTotal: "Prima total",
      paymentFrequency: "Forma de pago",
      deductible: "Franquicia",
      signatureStatus: "Firma",
    },
  },
  vehicleInsurance: {
    eyebrow: "Vehículo",
    title: "Seguro del vehículo",
    actionBack: "Volver al vehículo",
    emptyState: "Todavía no hay seguro registrado.",
    documentLinkLabel: "Abrir documentación",
    coverageIncluded: "Incluida",
    coverageExcluded: "No incluida",
    sections: {
      policy: "Póliza",
      insurer: "Aseguradora",
      policyHolder: "Tomador",
      vehicle: "Vehículo",
      coverages: "Coberturas",
      compensation: "Indemnización pérdida total",
      premium: "Prima",
      signature: "Firma electrónica",
      documents: "Documentación",
    },
    labels: {
      policyNumber: "Número",
      policySupplement: "Suplemento",
      policyType: "Tipo",
      issueDate: "Fecha emisión",
      effectiveDate: "Fecha efecto",
      expiryDate: "Vencimiento",
      duration: "Duración",
      revaluation: "Revalorización",
      insurerName: "Nombre",
      insurerTaxId: "CIF",
      insurerAddress: "Domicilio social",
      holderName: "Nombre",
      holderDni: "DNI",
      holderBirthDate: "Fecha nacimiento",
      holderAddress: "Dirección",
      holderPostalCode: "Código postal",
      holderCity: "Localidad",
      holderRegion: "Provincia",
      holderPhone: "Teléfono",
      holderEmail: "Email",
      holderLicenseType: "Permiso",
      holderLicenseValidFrom: "Válido desde",
      vehicleModel: "Modelo",
      vehicleType: "Tipo",
      vehiclePlate: "Matrícula",
      vehicleAge: "Antigüedad",
      vehicleUsage: "Uso",
      vehicleCirculationArea: "Ámbito circulación",
      vehicleUsualZone: "Zona habitual",
      coverageMandatoryLiability: "RC obligatoria",
      coverageSupplementaryLiability: "RC suplementaria",
      coverageDriverDeath: "Seguro conductor (fallecimiento)",
      coverageDriverDisability: "Seguro conductor (invalidez)",
      coverageDriverMedical: "Seguro conductor (asistencia sanitaria)",
      coverageLegalDefense: "Defensa jurídica",
      coverageRoadside: "Asistencia en viaje",
      coverageFire: "Incendio",
      coverageTheft: "Robo",
      coverageWindows: "Lunas",
      coverageOwnDamage: "Daños propios",
      coverageOwnDamageDeductible: "Franquicia daños propios",
      coverageWeather: "Fenómenos atmosféricos",
      coverageWildlife: "Atropello especies cinegéticas",
      compensationFirstTwoYears: "Primeros 2 años",
      compensationThirdYear: "Tercer año",
      compensationFromFourthYear: "Desde cuarto año",
      premiumNet: "Prima neta",
      premiumDiscounts: "Descuentos",
      premiumTaxes: "Impuestos",
      premiumConsortium: "Consorcio",
      premiumTotal: "Prima total",
      premiumPaymentFrequency: "Forma de pago",
      premiumPaymentMethod: "Medio de pago",
      signaturePlatform: "Plataforma",
      signatureStatus: "Estado",
      signatureSignedAt: "Fecha firma",
      signatureMethod: "Método",
      documentLink: "Enlace",
    },
  },
  vehiclePurchase: {
    eyebrow: "Vehículo",
    title: "Compra del vehículo",
    actionBack: "Volver al vehículo",
    emptyState: "Todavía no hay compra registrada.",
    offerTitle: "Oferta",
    dealerTitle: "Concesionario",
    advisorTitle: "Asesor comercial",
    customerTitle: "Cliente",
    vehicleTitle: "Vehículo",
    optionsTitle: "Opciones",
    optionsEmpty: "No hay opciones registradas.",
    economicDetailTitle: "Detalle económico",
    summaryTitle: "Resumen de la operación",
    labels: {
      issueDate: "Fecha de emisión",
      validUntil: "Válida hasta",
      offerNumber: "Número de oferta",
      customerNumber: "Número de cliente",
      dealerName: "Nombre",
      dealerAddress: "Dirección",
      dealerPhone: "Teléfono",
      dealerEmail: "Email",
      advisorName: "Nombre",
      advisorPhone: "Teléfono",
      advisorEmail: "Email",
      customerFirstName: "Nombre",
      customerLastName: "Apellidos",
      customerPhone: "Teléfono",
      customerEmail: "Email",
      vehicleModel: "Modelo",
      vehicleTransmission: "Cambio",
      vehicleTrim: "Acabado",
      vehicleFuel: "Combustible",
      vehiclePowerKw: "Potencia (kW)",
      vehiclePowerCv: "Potencia (CV)",
      vehicleEmissions: "CO2 WLTP (g/km)",
      optionsTotalBase: "Opciones base",
      optionsTotalPvp: "Opciones PVP",
      servicesTotal: "Servicios",
      accessoriesTotal: "Accesorios",
      vehicleBasePrice: "Vehículo base",
      vehiclePvpPrice: "Vehículo PVP",
      campaignBase: "Campaña base",
      campaignPvp: "Campaña PVP",
      vatAmount: "IVA",
      registrationTaxAmount: "Impuesto matriculación",
      taxDeduction: "Deducción impuestos",
      vehicleSubtotalBase: "Subtotal base",
      vehicleSubtotalPvp: "Subtotal PVP",
      summaryServices: "Servicios",
      summaryAccessories: "Accesorios",
      summarySupplies: "Suplidos",
      totalWithoutTradeIn: "Total sin recompra",
      tradeInValue: "Valoración usado",
      totalToPay: "Total a pagar",
      optionDescription: "Opción",
      optionBasePrice: "Base",
      optionPvpPrice: "PVP",
    },
  },
  vehicleMaintenanceHistory: {
    eyebrow: "Vehículo",
    title: "Historial de mantenimientos",
    actionBack: "Volver al vehículo",
    upcomingTitle: "Próximos mantenimientos",
    upcomingDescription: "Plan de mantenimiento previsto a partir de la entrega del vehículo.",
    upcomingEmpty: "No hay plan de mantenimiento configurado.",
    dueDateLabel: "Vencimiento",
    dueKmLabel: "Kilometraje objetivo",
    tasksLabel: "Incluye",
    notesLabel: "Notas",
    estimatedLabel: "estimado",
    serviceDateLabel: "Fecha",
    odometerLabel: "KM",
    markDoneLabel: "Marcar como hecho",
  },
  maintenanceDetail: {
    eyebrow: "Mantenimiento",
    actionBack: "Volver al vehículo",
    detailTitle: "Detalle",
    vehicleTitle: "Vehículo",
    workDetailTitle: "Detalle de trabajos",
    labels: {
      date: "Fecha",
      workshop: "Taller",
      odometer: "Odómetro",
      cost: "Coste",
    },
    sections: {
      jobs: "Trabajos",
      parts: "Piezas",
      totals: "Importes",
    },
    table: {
      concept: "Concepto",
      amount: "Importe",
    },
  },
  vehiclesList: {
    countLabel: { singular: "vehículo", plural: "vehículos" },
  },
  button: {
    loading: "Cargando",
  },
  units: {
    kwh: "kWh",
    m3: "m³",
    km: "km",
    eur: "€",
    liters: "L",
    cc: "cc",
    kw: "kW",
    gkm: "g/km",
    kg: "kg",
    days: "días",
  },
} as const;
