export const labels = {
  meta: {
    title: "Home Manager",
    description: "Panel de control para la gestión del hogar.",
  },
  common: {
    panelActiveLabel: "panel activo",
    homesActiveLabel: "viviendas activas",
    vehiclesActiveLabel: "vehículos activos",
    backToHome: "Volver al inicio",
    backToPanel: "Volver al panel",
    backToSelector: "Volver al selector",
    backToList: "Volver al listado",
    backToVehicle: "Volver al vehículo",
    open: "Abrir",
    view: "Ver",
    viewDetail: "Ver detalle",
    openPanel: "Abrir panel",
    viewBills: "Ver facturas",
    soon: "Próximamente",
    emptyValue: "-",
    noExtraDetails: "Sin detalles extra",
    noAdditionalDetails: "Sin detalles adicionales.",
    languageLabel: "Idioma",
    languageOptions: {
      es: "Español",
      en: "Inglés",
    },
  },
  dashboard: {
    eyebrow: "Panel de control",
    title: "Selecciona tu vivienda para gestionar tu hogar",
    description:
      "Visualiza facturas, consumo y tareas en un solo lugar. Cada vivienda tiene su propio espacio de control.",
    panelCode: "HM",
    homesSectionTitle: "Viviendas",
    homesCardTitle: "Selector de viviendas",
    homesCardDescription: "Accede al panel de cada casa con facturas, consumo y tareas pendientes.",
    homesLinkLabel: "Ver viviendas",
    vehiclesSectionTitle: "Vehículos",
    vehiclesCardTitle: "Control de mantenimiento",
    vehiclesCardDescription: "Consulta tus coches, talleres y gastos en un solo lugar.",
    vehiclesLinkLabel: "Ver vehículos",
    nextStepEyebrow: "Siguiente paso",
    nextStepTitle: "Conecta facturas de luz y revisa los costes por vivienda",
    nextStepDescription:
      "Define proveedores y categorías de coste para tener un desglose detallado por mes.",
    nextStepTag: "Próximamente",
  },
  homes: {
    eyebrow: "Viviendas",
    title: "Selecciona tu vivienda para gestionar tu hogar",
    description:
      "Visualiza facturas, consumo y tareas en un solo lugar. Cada vivienda tiene su propio espacio de control.",
    selectorTitle: "Selector de viviendas",
    cardBadge: "Vivienda",
    cardDescription: "Acceso directo a facturas, consumo y mantenimientos.",
  },
  homeDetail: {
    eyebrow: "Vivienda",
    description: "Accesos rápidos a los apartados principales de la vivienda.",
    servicesTitle: "Servicios principales",
    tiles: {
      energy: {
        title: "Luz",
        description: "Facturas y consumo eléctrico.",
        action: "Abrir",
      },
      water: {
        title: "Agua",
        description: "Recibos y seguimiento del consumo.",
        action: "Abrir",
      },
      gas: {
        title: "Gas",
        description: "Facturación y consumo de gas.",
        action: "Abrir",
      },
      insurance: {
        title: "Seguros",
        description: "Pólizas y vencimientos.",
        action: "Próximamente",
      },
    },
  },
  vehicles: {
    eyebrow: "Vehículos",
    title: "Gestiona tu flota doméstica",
    description: "Consulta fichas y mantenimientos recientes de cada coche.",
    listTitle: "Vehículos registrados",
    emptyList: "Todavía no hay vehículos registrados.",
    cardBadge: "Vehículo",
    statLabel: "mantenimientos",
    defaultIcon: "V",
  },
  energy: {
    eyebrow: "Luz",
    titlePrefix: "Facturas de",
    description: "Revisa los importes y períodos de facturación de electricidad.",
    listTitle: "Listado de facturas",
    emptyList: "Todavía no hay facturas registradas.",
  },
  water: {
    eyebrow: "Agua",
    titlePrefix: "Facturas de",
    description: "Revisa los importes y períodos de facturación de agua.",
    listTitle: "Listado de facturas",
    emptyList: "Todavía no hay facturas registradas.",
  },
  gas: {
    eyebrow: "Gas",
    titlePrefix: "Facturas de",
    description: "Revisa los importes y períodos de facturación de gas.",
    listTitle: "Listado de facturas",
    emptyList: "Todavía no hay facturas registradas.",
  },
  energyBill: {
    eyebrow: "Factura de luz",
    fallbackTitle: "Factura",
    summaryTitle: "Resumen",
    contractTitle: "Contrato",
    costTitle: "Desglose",
    costEmpty: "No hay líneas de coste asociadas.",
    costCategoryFallback: "Categoría",
    contractLabels: {
      tariff: "Tarifa",
      contract: "Contrato",
      cups: "CUPS",
      distributor: "Distribuidora",
      gridToll: "Peaje",
    },
  },
  waterBill: {
    eyebrow: "Factura de agua",
    fallbackTitle: "Factura",
    summaryTitle: "Resumen",
    contractTitle: "Contrato",
    costTitle: "Desglose",
    costEmpty: "No hay líneas de coste asociadas.",
    costCategoryFallback: "Categoría",
    extraLabels: {
      type: "Tipo",
      status: "Estado",
      totalToPay: "Total a pagar",
      cancels: "Anula",
    },
    contractLabels: {
      contract: "Contrato",
      meter: "Contador",
      usage: "Uso",
      supplyType: "Tipo suministro",
    },
  },
  gasBill: {
    eyebrow: "Factura de gas",
    fallbackTitle: "Factura",
    summaryTitle: "Resumen",
    contractTitle: "Suministro",
    costTitle: "Desglose",
    costEmpty: "No hay líneas de coste asociadas.",
    costCategoryFallback: "Categoría",
    extraLabels: {
      totalToPay: "Total a pagar",
      mandateReference: "Referencia mandato",
      conversionFactor: "Factor conversión",
      supplyPressure: "Presión suministro",
      peajes: "Peajes",
      cargos: "Cargos",
      cnmc: "CNMC",
      gts: "GTS",
      readingPrev: "Lectura anterior",
      readingCurr: "Lectura actual",
    },
    contractLabels: {
      accessTariff: "Tarifa acceso",
      commercialTariff: "Tarifa comercial",
      contract: "Contrato",
      cups: "CUPS",
      meter: "Contador",
      address: "Dirección",
    },
  },
  bills: {
    countLabel: { singular: "factura", plural: "facturas" },
    sortLabels: {
      date: "Fecha",
      invoice: "Factura",
      provider: "Proveedor",
      total: "Total",
      consumption: "Consumo",
    },
    filters: {
      provider: "Proveedor",
      year: "Año",
      all: "Todos",
    },
    headers: {
      detail: "Detalle",
      type: "Tipo",
      period: "Periodo",
      totalToPay: "Total a pagar",
      pdf: "PDF",
      cancels: "Anula",
    },
    pdfPending: "Pendiente de subir",
    invoiceFallback: "Factura",
  },
  billSummary: {
    provider: "Proveedor",
    totalAmount: "Importe total",
    consumption: "Consumo",
    issueDate: "Fecha de emisión",
    paymentDate: "Fecha de cargo",
    pdf: "PDF",
    openFile: "Abrir archivo",
  },
  billTypes: {
    factura_regular: "Regular",
    factura_sustitutiva: "Sustitutiva",
    factura_anulacion: "Anulación",
  },
  tableShell: {
    resultsLabel: { singular: "resultado", plural: "resultados" },
    noResults: "Sin resultados.",
  },
  maintenanceList: {
    countLabel: { singular: "mantenimiento", plural: "mantenimientos" },
  },
  maintenanceTable: {
    sortLabels: {
      date: "Fecha",
      title: "Mantenimiento",
      workshop: "Taller",
      cost: "Coste",
      odometer: "KM",
    },
    filters: {
      workshop: "Taller",
      year: "Año",
      all: "Todos",
    },
    headers: {
      summary: "Resumen",
      detail: "Detalle",
    },
    summary: {
      jobPrefix: "Trabajo",
      partsPrefix: "Piezas",
      totals: "Importes detallados",
    },
  },
  vehicleDetail: {
    eyebrow: "Vehículo",
    noPlate: "Sin matrícula registrada",
    sheetTitle: "Ficha",
    summaryTitle: "Resumen",
    notesTitle: "Notas",
    maintenanceHistoryTitle: "Historial de mantenimientos",
    emptyMaintenances: "Todavía no hay mantenimientos registrados.",
    labels: {
      brand: "Marca",
      model: "Modelo",
      year: "Año",
      plate: "Matrícula",
      vin: "VIN",
      maintenances: "Mantenimientos",
      lastService: "Último servicio",
      lastOdometer: "Último odómetro",
      lastCost: "Último coste",
    },
  },
  maintenanceDetail: {
    eyebrow: "Mantenimiento",
    actionBack: "Volver al vehículo",
    detailTitle: "Detalle",
    vehicleTitle: "Vehículo",
    workDetailTitle: "Detalle de trabajos",
    labels: {
      date: "Fecha",
      workshop: "Taller",
      odometer: "Odómetro",
      cost: "Coste",
    },
    sections: {
      jobs: "Trabajos",
      parts: "Piezas",
      totals: "Importes",
    },
    table: {
      concept: "Concepto",
      amount: "Importe",
    },
  },
  vehiclesList: {
    countLabel: { singular: "vehículo", plural: "vehículos" },
  },
  button: {
    loading: "Cargando",
  },
  units: {
    kwh: "kWh",
    m3: "m³",
    km: "km",
  },
} as const;
