export const labels = {
  meta: {
    title: "Home Manager",
    description: "Panel de control para la gestión del hogar.",
  },
  common: {
    panelActiveLabel: "panel activo",
    homesActiveLabel: "viviendas activas",
    vehiclesActiveLabel: "vehículos activos",
    backToHome: "Volver al inicio",
    backToPanel: "Volver al panel",
    backToSelector: "Volver al selector",
    backToList: "Volver al listado",
    backToVehicle: "Volver al vehículo",
    open: "Abrir",
    view: "Ver",
    viewDetail: "Ver detalle",
    openPanel: "Abrir panel",
    viewBills: "Ver facturas",
    soon: "Próximamente",
    emptyValue: "-",
    noExtraDetails: "Sin detalles extra",
    noAdditionalDetails: "Sin detalles adicionales.",
    languageLabel: "Idioma",
    languageOptions: {
      es: "Español",
      en: "Inglés",
    },
  },
  dashboard: {
    eyebrow: "Panel de control",
    title: "Panel general del hogar",
    description: "Consulta recordatorios, viviendas y vehículos desde un único punto.",
    panelCode: "HM",
    ticktickProjectsLink: "Proyectos TickTick",
    homeRemindersEyebrow: "Recordatorios",
    homeRemindersTitle: "Recordatorios combinados",
    homeRemindersDescription:
      "Vencidos recientes, pendientes de hoy y próximos 7 días de los vehículos.",
    homeRemindersMissingToken: "Configura TICKTICK_ACCESS_TOKEN para ver recordatorios.",
    homeRemindersMissingProject: "No hay proyectos TickTick asociados a vehículos.",
    homeRemindersError: "No se han podido cargar los recordatorios.",
    homeRemindersEmpty: "No hay recordatorios en los rangos configurados.",
    homeRemindersBucketEmpty: "Sin recordatorios en este rango.",
    homeRemindersBuckets: {
      overdueWeek: {
        title: "Vencidas 7 días",
        description: "Pendientes de la última semana",
      },
      today: {
        title: "Hoy",
        description: "Pendientes para hoy",
      },
      upcomingWeek: {
        title: "Próximos 7 días",
        description: "Vencen en los próximos 7 días",
      },
    },
    homesSectionTitle: "Viviendas",
    homesCardTitle: "Selector de viviendas",
    homesCardDescription: "Accede al panel de cada casa con facturas, consumo y tareas pendientes.",
    homesLinkLabel: "Ver viviendas",
    vehiclesSectionTitle: "Vehículos",
    vehiclesCardTitle: "Control de mantenimiento",
    vehiclesCardDescription: "Consulta tus coches, talleres y gastos en un solo lugar.",
    vehiclesLinkLabel: "Ver vehículos",
  },
  ticktickProjects: {
    eyebrow: "TickTick",
    title: "Proyectos disponibles",
    description: "Listado interno para configurar IDs de proyectos.",
    countLabel: {
      singular: "proyecto",
      plural: "proyectos",
    },
    tableHeaders: {
      name: "Proyecto",
      id: "ID",
      status: "Estado",
    },
    statusOpen: "Abierto",
    statusClosed: "Cerrado",
    missingTokenTag: "Falta token",
    missingTokenMessage: "Configura TICKTICK_ACCESS_TOKEN para ver proyectos.",
    errorTag: "Sin acceso",
    errorMessage: "No se han podido cargar los proyectos.",
    emptyMessage: "No hay proyectos disponibles.",
    hintMessage: "Copia el ID y úsalo en TICKTICK_INBOX_PROJECT_ID.",
  },
  homes: {
    eyebrow: "Viviendas",
    title: "Selecciona tu vivienda para gestionar tu hogar",
    description:
      "Visualiza facturas, consumo y tareas en un solo lugar. Cada vivienda tiene su propio espacio de control.",
    selectorTitle: "Selector de viviendas",
    cardBadge: "Vivienda",
    cardDescription: "Acceso directo a facturas, consumo y mantenimientos.",
  },
  homeDetail: {
    eyebrow: "Vivienda",
    description: "Accesos rápidos a los apartados principales de la vivienda.",
    servicesTitle: "Servicios principales",
    tiles: {
      energy: {
        title: "Luz",
        description: "Facturas y consumo eléctrico.",
        action: "Abrir",
      },
      water: {
        title: "Agua",
        description: "Recibos y seguimiento del consumo.",
        action: "Abrir",
      },
      gas: {
        title: "Gas",
        description: "Facturación y consumo de gas.",
        action: "Abrir",
      },
      insurance: {
        title: "Seguros",
        description: "Pólizas y vencimientos.",
        action: "Próximamente",
      },
    },
  },
  vehicles: {
    eyebrow: "Vehículos",
    title: "Gestiona tu flota doméstica",
    description: "Consulta fichas y mantenimientos recientes de cada coche.",
    listTitle: "Vehículos registrados",
    emptyList: "Todavía no hay vehículos registrados.",
    cardBadge: "Vehículo",
    statLabel: "mantenimientos",
    defaultIcon: "V",
  },
  energy: {
    eyebrow: "Luz",
    titlePrefix: "Facturas de",
    description: "Revisa los importes y períodos de facturación de electricidad.",
    listTitle: "Listado de facturas",
    emptyList: "Todavía no hay facturas registradas.",
    chartTitle: "Consumo eléctrico",
    chartSubtitle: "kWh e importe por factura",
    chartEmpty: "No hay consumo registrado para representar.",
    chartSeriesKwh: "Consumo (kWh)",
    chartSeriesAmount: "Importe (€)",
    chartAxisKwh: "kWh",
    chartAxisAmount: "€",
    comparison: {
      title: "Comparativa anual",
      description: "Importes, consumo y coste medio por kWh mes a mes.",
      empty: "No hay datos suficientes para comparar los años seleccionados.",
      actionLabel: "Ver comparativa",
      deltaLabel: "Diferencia",
      chartTitle: "Comparativa mensual",
      chartSubtitle: "Líneas superpuestas por año",
      chartMetricLabel: "Métrica",
      chartMetricAmount: "Importe",
      chartMetricUsage: "kWh",
      chartAxisAmount: "€",
      chartAxisUsage: "kWh",
      filters: {
        yearA: "Año base",
        yearB: "Año comparado",
        apply: "Aplicar",
      },
      columns: {
        month: "Mes",
        amount: "Importe",
        usage: "Consumo",
        eurPerUnit: "€/kWh",
        bill: "Factura",
        deltaAmount: "Δ Importe",
        deltaUsage: "Δ kWh",
      },
    },
  },
  water: {
    eyebrow: "Agua",
    titlePrefix: "Facturas de",
    description: "Revisa los importes y períodos de facturación de agua.",
    listTitle: "Listado de facturas",
    emptyList: "Todavía no hay facturas registradas.",
    chartTitle: "Consumo de agua",
    chartSubtitle: "m³ e importe por factura",
    chartEmpty: "No hay consumo registrado para representar.",
    chartSeriesM3: "Consumo (m³)",
    chartSeriesAmount: "Importe (€)",
    chartAxisM3: "m³",
    chartAxisAmount: "€",
    comparison: {
      title: "Comparativa anual",
      description: "Importes, consumo y coste medio por m³ mes a mes.",
      empty: "No hay datos suficientes para comparar los años seleccionados.",
      actionLabel: "Ver comparativa",
      deltaLabel: "Diferencia",
      chartTitle: "Comparativa mensual",
      chartSubtitle: "Líneas superpuestas por año",
      chartMetricLabel: "Métrica",
      chartMetricAmount: "Importe",
      chartMetricUsage: "m³",
      chartAxisAmount: "€",
      chartAxisUsage: "m³",
      filters: {
        yearA: "Año base",
        yearB: "Año comparado",
        apply: "Aplicar",
      },
      columns: {
        month: "Mes",
        amount: "Importe",
        usage: "Consumo",
        eurPerUnit: "€/m³",
        bill: "Factura",
        deltaAmount: "Δ Importe",
        deltaUsage: "Δ m³",
      },
    },
  },
  gas: {
    eyebrow: "Gas",
    titlePrefix: "Facturas de",
    description: "Revisa los importes y períodos de facturación de gas.",
    listTitle: "Listado de facturas",
    emptyList: "Todavía no hay facturas registradas.",
    chartTitle: "Consumo de gas",
    chartSubtitle: "kWh y m³ por factura",
    chartEmpty: "No hay consumo registrado para representar.",
    chartSeriesKwh: "Consumo (kWh)",
    chartSeriesM3: "Consumo (m³)",
    chartSeriesAmount: "Importe (€)",
    chartAxisKwh: "kWh",
    chartAxisM3: "m³",
    chartAxisAmount: "€",
    comparison: {
      title: "Comparativa anual",
      description: "Importes, consumo y coste medio por kWh mes a mes.",
      empty: "No hay datos suficientes para comparar los años seleccionados.",
      actionLabel: "Ver comparativa",
      deltaLabel: "Diferencia",
      chartTitle: "Comparativa mensual",
      chartSubtitle: "Líneas superpuestas por año",
      chartMetricLabel: "Métrica",
      chartMetricAmount: "Importe",
      chartMetricUsage: "kWh",
      chartAxisAmount: "€",
      chartAxisUsage: "kWh",
      filters: {
        yearA: "Año base",
        yearB: "Año comparado",
        apply: "Aplicar",
      },
      columns: {
        month: "Mes",
        amount: "Importe",
        usage: "Consumo",
        eurPerUnit: "€/kWh",
        bill: "Factura",
        deltaAmount: "Δ Importe",
        deltaUsage: "Δ kWh",
      },
    },
  },
  energyBill: {
    eyebrow: "Factura de luz",
    fallbackTitle: "Factura",
    summaryTitle: "Resumen",
    contractTitle: "Contrato",
    costTitle: "Desglose",
    costEmpty: "No hay líneas de coste asociadas.",
    costCategoryFallback: "Categoría",
    contractLabels: {
      tariff: "Tarifa",
      contract: "Contrato",
      cups: "CUPS",
      distributor: "Distribuidora",
      gridToll: "Peaje",
    },
  },
  waterBill: {
    eyebrow: "Factura de agua",
    fallbackTitle: "Factura",
    summaryTitle: "Resumen",
    contractTitle: "Contrato",
    costTitle: "Desglose",
    costEmpty: "No hay líneas de coste asociadas.",
    costCategoryFallback: "Categoría",
    extraLabels: {
      type: "Tipo",
      status: "Estado",
      totalToPay: "Total a pagar",
      cancels: "Anula",
    },
    contractLabels: {
      contract: "Contrato",
      meter: "Contador",
      usage: "Uso",
      supplyType: "Tipo suministro",
    },
  },
  gasBill: {
    eyebrow: "Factura de gas",
    fallbackTitle: "Factura",
    summaryTitle: "Resumen",
    contractTitle: "Suministro",
    costTitle: "Desglose",
    costEmpty: "No hay líneas de coste asociadas.",
    costCategoryFallback: "Categoría",
    extraLabels: {
      totalToPay: "Total a pagar",
      mandateReference: "Referencia mandato",
      conversionFactor: "Factor conversión",
      supplyPressure: "Presión suministro",
      peajes: "Peajes",
      cargos: "Cargos",
      cnmc: "CNMC",
      gts: "GTS",
      readingPrev: "Lectura anterior",
      readingCurr: "Lectura actual",
    },
    contractLabels: {
      accessTariff: "Tarifa acceso",
      commercialTariff: "Tarifa comercial",
      contract: "Contrato",
      cups: "CUPS",
      meter: "Contador",
      address: "Dirección",
    },
  },
  bills: {
    countLabel: { singular: "factura", plural: "facturas" },
    sortLabels: {
      date: "Fecha",
      invoice: "Factura",
      provider: "Proveedor",
      total: "Total",
      consumption: "Consumo",
    },
    filters: {
      provider: "Proveedor",
      year: "Año",
      all: "Todos",
    },
    headers: {
      detail: "Detalle",
      type: "Tipo",
      period: "Periodo",
      totalToPay: "Total a pagar",
      pdf: "PDF",
      cancels: "Anula",
    },
    pdfPending: "Pendiente de subir",
    invoiceFallback: "Factura",
  },
  billSummary: {
    provider: "Proveedor",
    totalAmount: "Importe total",
    consumption: "Consumo",
    issueDate: "Fecha de emisión",
    paymentDate: "Fecha de cargo",
    pdf: "PDF",
    openFile: "Abrir archivo",
  },
  billTypes: {
    factura_regular: "Regular",
    factura_sustitutiva: "Sustitutiva",
    factura_anulacion: "Anulación",
  },
  tableShell: {
    resultsLabel: { singular: "resultado", plural: "resultados" },
    noResults: "Sin resultados.",
  },
  maintenanceList: {
    countLabel: { singular: "mantenimiento", plural: "mantenimientos" },
  },
  maintenanceTable: {
    sortLabels: {
      date: "Fecha",
      title: "Mantenimiento",
      workshop: "Taller",
      cost: "Coste",
      odometer: "KM",
    },
    filters: {
      workshop: "Taller",
      year: "Año",
      all: "Todos",
    },
    headers: {
      summary: "Resumen",
      detail: "Detalle",
    },
    summary: {
      jobPrefix: "Trabajo",
      partsPrefix: "Piezas",
      totals: "Importes detallados",
    },
  },
  vehicleDetail: {
    eyebrow: "Vehículo",
    noPlate: "Sin matrícula registrada",
    sheetTitle: "Ficha",
    summaryTitle: "Resumen",
    notesTitle: "Notas",
    maintenanceHistoryTitle: "Historial de mantenimientos",
    emptyMaintenances: "Todavía no hay mantenimientos registrados.",
    purchaseActionLabel: "Ver más detalles",
    remindersEyebrow: "TickTick",
    remindersTitle: "Recordatorios del vehículo",
    remindersDescription: "Tareas del proyecto asociado a este vehículo.",
    remindersProjectsLink: "Proyectos",
    remindersCountLabel: {
      singular: "recordatorio",
      plural: "recordatorios",
    },
    remindersTabs: {
      overdueRecent: "Vencidas 30 días",
      today: "Hoy",
      upcoming: "Próximas",
      noDate: "Sin fecha",
      overdueLong: "Vencidas > 30 días",
    },
    remindersDueLabel: "vence",
    remindersNoDueDate: "Sin fecha",
    remindersEmpty: "No hay recordatorios pendientes.",
    remindersMissingProjectTag: "Sin proyecto",
    remindersMissingProjectMessage: "Configura el proyecto TickTick del vehículo.",
    remindersMissingTokenTag: "Falta token",
    remindersMissingTokenMessage: "Configura TICKTICK_ACCESS_TOKEN para ver recordatorios.",
    remindersErrorTag: "Sin acceso",
    remindersErrorMessage: "No se han podido cargar los recordatorios.",
    labels: {
      brand: "Marca",
      model: "Modelo",
      year: "Año",
      plate: "Matrícula",
      vin: "VIN",
      maintenances: "Mantenimientos",
      lastService: "Último servicio",
      lastOdometer: "Último odómetro",
      lastCost: "Último coste",
      purchaseDate: "Fecha de compra",
      purchaseTotal: "Total a pagar",
      purchaseModel: "Modelo compra",
      purchaseDealer: "Concesionario",
    },
  },
  vehiclePurchase: {
    eyebrow: "Vehículo",
    title: "Compra del vehículo",
    actionBack: "Volver al vehículo",
    emptyState: "Todavía no hay compra registrada.",
    offerTitle: "Oferta",
    dealerTitle: "Concesionario",
    advisorTitle: "Asesor comercial",
    customerTitle: "Cliente",
    vehicleTitle: "Vehículo",
    optionsTitle: "Opciones",
    optionsEmpty: "No hay opciones registradas.",
    economicDetailTitle: "Detalle económico",
    summaryTitle: "Resumen de la operación",
    labels: {
      issueDate: "Fecha de emisión",
      validUntil: "Válida hasta",
      offerNumber: "Número de oferta",
      customerNumber: "Número de cliente",
      dealerName: "Nombre",
      dealerAddress: "Dirección",
      dealerPhone: "Teléfono",
      dealerEmail: "Email",
      advisorName: "Nombre",
      advisorPhone: "Teléfono",
      advisorEmail: "Email",
      customerFirstName: "Nombre",
      customerLastName: "Apellidos",
      customerPhone: "Teléfono",
      customerEmail: "Email",
      vehicleModel: "Modelo",
      vehicleTransmission: "Cambio",
      vehicleTrim: "Acabado",
      vehicleFuel: "Combustible",
      vehiclePowerKw: "Potencia (kW)",
      vehiclePowerCv: "Potencia (CV)",
      vehicleEmissions: "CO2 WLTP (g/km)",
      optionsTotalBase: "Opciones base",
      optionsTotalPvp: "Opciones PVP",
      servicesTotal: "Servicios",
      accessoriesTotal: "Accesorios",
      vehicleBasePrice: "Vehículo base",
      vehiclePvpPrice: "Vehículo PVP",
      campaignBase: "Campaña base",
      campaignPvp: "Campaña PVP",
      vatAmount: "IVA",
      registrationTaxAmount: "Impuesto matriculación",
      taxDeduction: "Deducción impuestos",
      vehicleSubtotalBase: "Subtotal base",
      vehicleSubtotalPvp: "Subtotal PVP",
      summaryServices: "Servicios",
      summaryAccessories: "Accesorios",
      summarySupplies: "Suplidos",
      totalWithoutTradeIn: "Total sin recompra",
      tradeInValue: "Valoración usado",
      totalToPay: "Total a pagar",
      optionDescription: "Opción",
      optionBasePrice: "Base",
      optionPvpPrice: "PVP",
    },
  },
  maintenanceDetail: {
    eyebrow: "Mantenimiento",
    actionBack: "Volver al vehículo",
    detailTitle: "Detalle",
    vehicleTitle: "Vehículo",
    workDetailTitle: "Detalle de trabajos",
    labels: {
      date: "Fecha",
      workshop: "Taller",
      odometer: "Odómetro",
      cost: "Coste",
    },
    sections: {
      jobs: "Trabajos",
      parts: "Piezas",
      totals: "Importes",
    },
    table: {
      concept: "Concepto",
      amount: "Importe",
    },
  },
  vehiclesList: {
    countLabel: { singular: "vehículo", plural: "vehículos" },
  },
  button: {
    loading: "Cargando",
  },
  units: {
    kwh: "kWh",
    m3: "m³",
    km: "km",
    eur: "€",
  },
} as const;
